---

- name: Check User Folder
  hosts: downloader
  gather_facts: no

  tasks:
    - name: Create Temp file unser User folder
      copy:
        content: "hello world\n"
        dest: /mnt/user/temp/testfile.txt
        owner: "99"
        group: "users"
