---

- name: Check User Folder
  hosts: unraid
  gather_facts: no
  vars:
    my_move_up_dir: "{{ move_up_dir }}"

  tasks:
    - name: Find files in folder
      find:
        paths: "{ my_move_up_dir }"
        register: files_matched
    
    - debug:
        msg: "{{ files_matched }}"
        
