---

- name: Check User Folder
  hosts: downloader
  gather_facts: no
  vars:
    my_move_up_dir: "{{ move_up_dir }}"

  tasks:
    - debug:
        msg: "{{ my_move_up_dir }}"

    - name: Find files in folder
      find:
        paths: "{{ my_move_up_dir }}"
      register: files_matched
    
    - debug:
        msg: "{{ files_matched }}"

