---

- name: Check User Folder
  hosts: downloader
  gather_facts: no
  vars:
    my_move_up_dir: "{{ move_up_dir }}"

  tasks:
    - debug:
        msg: "Working folder: {{ my_move_up_dir }}"

    - name: Find files in folder
      find:
        paths: "{{ my_move_up_dir }}"
        patterns: "*.*"
        recurse: yes
      register: files_matched
      become: yes
    
    - debug:
        msg: "{{ files_matched }}"
    
    - name: Move file to parent
      command: mv "{{ item.path }}" ..
      with_items: "{{ files_matched.files }}"
      register: cmd_out

    - debug:
        msg: "{{ cmd_out }}"


